apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
      - name: db-postgres
        image: postgres:15-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: password
          - name: POSTGRES_DB
            value: ecommerce
          - name: POSTGRES_HOST
            value: localhost
          - name: POSTGRES_PORT
            value: '5432'
      #   volumeMounts:
      #   - name: postgres-persistent-storage
      #     mountPath: /var/lib/postgres/data
      # volumes:
      # - name: postgres-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: postgres-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres-srvc
spec:
  type: ClusterIP
  selector:
    app: db-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: postgres-pv-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi # Adjust storage size as needed
