apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      initContainers:
        - name: init-migration
          image: rovilay/ecommerce-db-migration
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_DB
              value: ecommerce
            - name: POSTGRES_HOST
              value: db-postgres-srvc
            - name: POSTGRES_PORT
              value: '5432'
            - name: DB_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=disable"
          command: ["/bin/sh", "-c"]
          args:
          - |
            # Wait for the PostgreSQL server to start
            until pg_isready -h $(POSTGRES_HOST) -U postgres -d ecommerce -t 3; do
              echo "Waiting for PostgreSQL..."
              sleep 2
            done

            # Run your database migrations
            ./bin/migration # Replace with your actual migration command
      containers:
        - name: product
          image: rovilay/ecommerce-product-service:latest
          env:
            - name: PRODUCT_SERVER_PORT
              value: '3001'
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: POSTGRES_DB
              value: ecommerce
            - name: POSTGRES_HOST
              value: db-postgres-srvc
            - name: POSTGRES_PORT
              value: '5432'
            - name: DB_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=disable"
          readinessProbe:
            exec:
              command:
              - sh
              - -c
              - pg_isready -h db-postgres-srvc -U postgres -d ecommerce
            initialDelaySeconds: 5
            periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: product-srvc
spec:
  type: ClusterIP
  selector:
    app: product
  ports:
    - name: product
      protocol: TCP
      port: 3001
      targetPort: 3001
